Repository tokitouq/CoreProject-Frontend, pull requests merged in 2023-05, with the labels that each got.

#106 Homepage mobile design
  src/routes/+layout.svelte
  src/routes/+page.svelte
Labels: enhancement

#108 Fix Homepage mobile view design
  src/app.scss
  src/routes/+layout.svelte
  src/routes/+page.svelte
Labels: enhancement, good first issue

#162 :sparkles: Add new popover configurations
  package-lock.json
  package.json
  src/lib/components/shared/tippies/my_list_anime_details.svelte
  src/routes/+page.svelte
Labels: enhancement

#166 :sparkles: Lazy loading images
  src/lib/components/shared/image/image.svelte
  src/lib/components/shared/image/image_loader.svelte
  src/lib/components/shared/intersection_observer.svelte
  src/routes/+page.svelte
Labels: enhancement

#175 Fix intersection observer
  src/lib/components/shared/intersection_observer.svelte
  src/routes/+page.svelte
Labels: duplicate, enhancement

#177 Fix slider controling timer via viewport
  src/lib/components/shared/image/image_loader.svelte
  src/lib/components/shared/image/intersection_observer.svelte
  src/routes/+page.svelte
Labels: bug

#205 Refactor anime info page
  src/lib/components/pages/anime_info/anime_episodes.svelte
  src/lib/components/pages/anime_info/anime_full_details.svelte
  src/lib/components/pages/anime_info/anime_main_details.svelte
  src/lib/components/pages/anime_info/index.svelte
  src/lib/components/pages/anime_info/sidebar_details.svelte
  src/lib/components/shared/image/intersection_observer.svelte
  src/lib/data/mock/forum_posts.ts
  src/lib/icons/emoji.svelte
  src/routes/[...slugs=myanimelist]/[id=int]/+page.svelte
Labels: enhancement
