Repository tokitouq/CoreProject-Frontend, pull requests merged in 2023-08, with the labels that each got.

#527 feat: add smartypants
  package-lock.json
  package.json
  src/app.css
  src/lib/components/shared/markdown.svelte
Labels: enhancement

#582 feat: move to skeleton v2
  package-lock.json
  package.json
  src/app.html
  src/app.postcss
  src/lib/themes/kokoro.ts
  src/routes/+layout.svelte
  tailwind.config.ts
Labels: enhancement, dependencies

#597 feat: add purgecss
  package-lock.json
  package.json
  vite.config.ts
Labels: enhancement

#602 style: Scrollbar track background
  src/lib/components/shared/scroll_area.svelte
Labels: bug fix

#605 style: Fancy progress bar
  src/nprogress.scss
Labels: enhancement

#636 feat: better `tippy.js` calculations
  src/routes/+page.svelte
Labels: enhancement

#640 refractor: codebase
  src/lib/components/pages/anime_info/index.svelte
  src/lib/components/pages/episode/index.svelte
  src/lib/components/shared/comment.svelte
  src/lib/components/shared/forum_posts.svelte
  src/lib/components/shared/image/image.svelte
  src/lib/components/shared/image/image_loader.svelte
  src/lib/components/shared/image/intersection_observer.svelte
  src/lib/components/shared/markdown.svelte
  src/lib/components/shared/vercel_hover.svelte
  src/lib/components/tippies/anime_card.svelte
  src/lib/components/tippies/my_list_anime_details.svelte
  src/lib/components/tippies/profile_dropdown.svelte
  src/lib/store/timer.ts
  src/routes/+page.svelte
  src/routes/[...slugs=myanimelist]/[id=int]/+page.svelte
  src/routes/anilist/[id=int]/+page.svelte
  src/routes/explore/+page.svelte
  src/routes/kitsu/[id=int]/+page.svelte
  src/routes/user/login/1.svelte
  src/routes/user/register/1.svelte
  src/routes/user/register/2.svelte
Labels: enhancement
